CURRENT = [
("methods/42/(.*)", "/article/in-situ-hybridisation-to-alpha-satellite-sequences/"),
("methods/1535/(.*)", "/article/install-haiku-under-mac-os-x-with-virtualbox/"),
("methods/1511/(.*)", "/article/purification-of-anti-peptide-antibody/"),
("methods/1341/(.*)", "/article/pm-buffer/"),
("methods/13/(.*)", "/article/primary-monocyte-differentiation-dcs-gm-csfil-4/"),
("methods/1418/(.*)", "/article/2x-rapid-ligation-buffer/"),
("methods/27/(.*)", "/article/carnoys-fluid-fixation/"),
("methods/1509/(.*)", "/article/microtubule-spindowns-from-extracts/"),
("methods/1456/(.*)", "/article/8-paraformaldehyde-for-immunofluorescence/"),
("methods/1433/(.*)", "/article/embryo-4d-microscopy-mounting/"),
("methods/1503/(.*)", "/article/execute-last-command-as-root/"),
("methods/1442/(.*)", "/article/chemiluminescent-detection/"),
("methods/34/(.*)", "/article/ethanol-fixation-for-flow-cytometry/"),
("methods/1368/(.*)", "/article/05-m-na2co3/"),
("methods/1358/(.*)", "/article/100-mm-mggtp/"),
("methods/1534/(.*)", "/article/find-all-files-containing-a-given-string/"),
("methods/1361/(.*)", "/article/36-mm-brefeldin-a/"),
("methods/1539/(.*)", "/article/speed-up-matlab-on-macos-x/"),
("methods/1340/(.*)", "/article/mounting-media/"),
("methods/1516/(.*)", "/article/get-file-type-information-from-the-command-line/"),
("methods/51/(.*)", "/article/retroviral-infection-of-phks/"),
("methods/1394/(.*)", "/article/heparan-sulfate-chain-analysis/"),
("methods/1353/(.*)", "/article/05-m-edta/"),
("methods/1497/(.*)", "/article/use-gnome-looking-glass-for-debugging/"),
("methods/21/(.*)", "/article/10x-tris-buffer/"),
("methods/1463/(.*)", "/article/x-gal-overlay-assay-for-yeast-plates/"),
("methods/1356/(.*)", "/article/1-m-kcl-stock/"),
("methods/1354/(.*)", "/article/05-m-egta-stock/"),
("methods/1347/(.*)", "/article/homogenization-buffer/"),
("methods/1499/(.*)", "/article/csf-extract-prep-for-spindle-assembly/"),
("methods/38/(.*)", "/article/dapi-counterstain-adherent-cellssections/"),
("methods/1518/(.*)", "/article/get-a-list-of-all-processes-not-run-by-you/"),
("methods/1538/(.*)", "/article/using-email-to-sms-gateways-to-send-free-sms/"),
("methods/1496/(.*)", "/article/debug-gnome-shell/"),
("methods/1513/(.*)", "/article/piping-between-shells/"),
("methods/48/(.*)", "/article/brdu-incorporation-for-raft-cultures/"),
("methods/1379/(.*)", "/article/determining-dna-concentrations-for-ligations/"),
("methods/120/(.*)", "/article/dna-extraction-from-agarose-gels-dialysis-tubing/"),
("methods/50/(.*)", "/article/collagen-gel-containing-3t3-fibroblasts/"),
("methods/1344/(.*)", "/article/isolation-buffer/"),
("methods/1357/(.*)", "/article/10-m-naoh/"),
("methods/1383/(.*)", "/article/lacritin-stimulated-cell-proliferation-assay/"),
("methods/1427/(.*)", "/article/bacterial-mediated-rnai/"),
("methods/45/(.*)", "/article/transformation-of-plasmid-dna-to-e-coli/"),
("methods/1507/(.*)", "/article/use-ifconfigme-to-return-your-ip-and-host/"),
("methods/1460/(.*)", "/article/measuring-dna-contour-lengths-with-imagej/"),
("methods/1387/(.*)", "/article/transformation-of-xli-blue-mrf-competent-cells/"),
("methods/1512/(.*)", "/article/fixingpelleting-chromatin-for-immunofluorescence/"),
("methods/9/(.*)", "/article/b-cell-enrichment-via-dynabeads/"),
("methods/41/(.*)", "/article/apes-treatment-of-slides/"),
("methods/1419/(.*)", "/article/5x-long-pcr-buffer/"),
("methods/1362/(.*)", "/article/30-x-naf/"),
("methods/1424/(.*)", "/article/ems-mutagenesis/"),
("methods/1525/(.*)", "/article/syntax-highlighting-with-django-and-markdown/"),
("methods/1372/(.*)", "/article/lacritin-ip3-assay/"),
("methods/1447/(.*)", "/article/immunohistochemistry-cultured-cellsmonolayers/"),
("methods/1437/(.*)", "/article/c-elegans-single-worm-pcr/"),
("methods/1360/(.*)", "/article/5-m-nacl/"),
("methods/1359/(.*)", "/article/100-mm-mgatp-stock/"),
("methods/1457/(.*)", "/article/haemotoxylin-and-eosin-staining/"),
("methods/1471/(.*)", "/article/show-warning-in-prompt-when-shell-loses-directory/"),
("methods/1438/(.*)", "/article/plc-buffer-for-immunoprecipitation/"),
("methods/1531/(.*)", "/article/display-external-rss-feeds-on-your-wordpress-blog/"),
("methods/35/(.*)", "/article/formaldehyde-fixation-for-flow-cytometry/"),
("methods/1523/(.*)", "/article/remove-duplicate-lines-from-text-files-with-sort/"),
("methods/1514/(.*)", "/article/find-all-running-processes-of-a-program/"),
("methods/1454/(.*)", "/article/sodium-citrate-buffer/"),
("methods/1339/(.*)", "/article/pbs-5x-in-500-mls/"),
("methods/43/(.*)", "/article/retrovirus-titration/"),
("methods/1384/(.*)", "/article/tear-collection-method/"),
("methods/1346/(.*)", "/article/10-x-column-buffer/"),
("methods/30/(.*)", "/article/neutral-buffered-formalin-fixation/"),
("methods/1421/(.*)", "/article/01-m-glycine-hcl-ph-27/"),
("methods/1367/(.*)", "/article/3-m-ki/"),
("methods/1469/(.*)", "/article/silica-suspension-for-plasmid-recovery/"),
("methods/1439/(.*)", "/article/c-elegans-immunoprecipitation/"),
("methods/1342/(.*)", "/article/valap/"),
("methods/25/(.*)", "/article/acetic-alcohol-fixation/"),
("methods/1495/(.*)", "/article/6x-dna-loading-buffer-for-agarose/"),
("methods/1449/(.*)", "/article/cresyl-violet-staining-nissl-staining/"),
("methods/1515/(.*)", "/article/reload-bash_profile-without-logging-out/"),
("methods/1431/(.*)", "/article/t-a-cloning-vectors/"),
("methods/1472/(.*)", "/article/add-git-branch-name-to-terminal-prompt-mac/"),
("methods/1466/(.*)", "/article/using-a-gel-doc-system/"),
("methods/1364/(.*)", "/article/30-mm-mg-gtp-g-s/"),
("methods/29/(.*)", "/article/hellys-fluid-fixation/"),
("methods/1537/(.*)", "/article/customize-directory-colors/"),
("methods/1493/(.*)", "/article/cell-culture-freezing-media/"),
("methods/1458/(.*)", "/article/neuron-recovery-of-neurobiotinbiocytin-cells/"),
("methods/1532/(.*)", "/article/highlight-authors-comments-on-wordpress-blog/"),
("methods/1465/(.*)", "/article/lb-agar-plates/"),
("methods/1371/(.*)", "/article/cell-adhesion/"),
("methods/33/(.*)", "/article/zenkers-fluid-fixation/"),
("methods/1430/(.*)", "/article/c-elegans-total-genomic-dna-preparation/"),
("methods/1389/(.*)", "/article/excision-of-clones-as-pbluescript-from-lzapii/"),
("methods/17/(.*)", "/article/metabolite-extraction-from-supernatant-cells/"),
("methods/18/(.*)", "/article/100mm-tris-buffer/"),
("methods/1335/(.*)", "/article/isolation-of-ldl-from-human-plasma/"),
("methods/16/(.*)", "/article/generic-quantitative-sandwich-elisa/"),
("methods/1470/(.*)", "/article/setup-android-development-with-eclipse-on-mac/"),
("methods/1432/(.*)", "/article/cosmid-low-copy-plasmid-prep/"),
("methods/1462/(.*)", "/article/dot-blot-analysis-with-imagej/"),
("methods/1349/(.*)", "/article/pbs-1x-in-1l/"),
("methods/1529/(.*)", "/article/change-the-desktop-directory-on-linux/"),
("methods/1440/(.*)", "/article/transformation-of-frozen-saccharomyces-cerevisiae/"),
("methods/23/(.*)", "/article/preparation-for-microdissection-polyester/"),
("methods/1510/(.*)", "/article/testing-rabbit-bleeds-by-elisa/"),
("methods/1390/(.*)", "/article/rotary-shadowing/"),
("methods/1533/(.*)", "/article/django-ajax-threaded-comments-using-only-jquery/"),
("methods/1386/(.*)", "/article/preparation-of-competent-xli-blue-mrf-cells/"),
("methods/39/(.*)", "/article/cells-in-suspension/"),
("methods/1429/(.*)", "/article/frozen-yeast-competent-cells/"),
("methods/1343/(.*)", "/article/20-x-energy-regeneration-system/"),
("methods/1453/(.*)", "/article/mowiol-aqueous-mounting-media/"),
("methods/1425/(.*)", "/article/tmp-uv-integration/"),
("methods/1455/(.*)", "/article/chrome-alum-gelatin-slide-coating/"),
("methods/1422/(.*)", "/article/c-elegans-embryo-staining/"),
("methods/1444/(.*)", "/article/purification-of-6x-his-proteins/"),
("methods/1501/(.*)", "/article/hss-depletion-conditions-for-xkcm1/"),
("methods/1464/(.*)", "/article/dna-extraction-chelex/"),
("methods/1504/(.*)", "/article/automatic-unzipuntar-using-correct-tool/"),
("methods/12/(.*)", "/article/differentiation-to-m1m2-macrophages-gm-csfm-csf/"),
("methods/1336/(.*)", "/article/extracting-cholesterol-and-lipids-from-cells/"),
("methods/1527/(.*)", "/article/installing-google-earth-on-ubuntu/"),
("methods/11/(.*)", "/article/hl-60-differentiation-to-neutrophilsmonocytes/"),
("methods/1385/(.*)", "/article/preparation-of-sonicated-salmon-sperm-dna/"),
("methods/1378/(.*)", "/article/phosphatase-removal-of-po4-groups-from-dna/"),
("methods/1441/(.*)", "/article/c-elegans-microinjection/"),
("methods/20/(.*)", "/article/10-ammonium-persulphate-solution/"),
("methods/1528/(.*)", "/article/collaborate-in-the-shell-with-screen-multiuser/"),
("methods/1375/(.*)", "/article/agarose-gel-electrophoresis/"),
("methods/1468/(.*)", "/article/initialize-git-repository-from-local-files/"),
("methods/26/(.*)", "/article/bouins-fluid-fixation/"),
("methods/1435/(.*)", "/article/colloidal-coomassie-blue-solution/"),
("methods/1490/(.*)", "/article/install-homebrew-package-manager-for-mac/"),
("methods/1366/(.*)", "/article/100-mm-sodium-orthovanadate/"),
("methods/1392/(.*)", "/article/lacritin-calcium-signaling-assay/"),
("methods/1355/(.*)", "/article/1m-dithiothreitol-dtt/"),
("methods/1519/(.*)", "/article/use-bash-brace-expansion-to-save-hoursdays/"),
("methods/1491/(.*)", "/article/control-r-through-your-history/"),
("methods/1522/(.*)", "/article/control-console-with-sysreq/"),
("methods/1428/(.*)", "/article/m9-plates-leu/"),
("methods/1459/(.*)", "/article/nickel-dab-n-dab-labeling/"),
("methods/1377/(.*)", "/article/dna-fragment-isolation/"),
("methods/1502/(.*)", "/article/in-gel-tryptic-digest-for-protein-id-by-ms/"),
("methods/10/(.*)", "/article/restoration-from-dmso-cryopreservation/"),
("methods/1420/(.*)", "/article/antibody-purification-using-blotted-antigen/"),
("methods/1536/(.*)", "/article/control-memcached-from-the-command-line/"),
("methods/31/(.*)", "/article/michels-fixative-for-immunofluorescence/"),
("methods/14/(.*)", "/article/macs-cd14-separation-of-monocytes/"),
("methods/1434/(.*)", "/article/embryo-4d-micro-zeiss-axioplan-2-axiovision-45/"),
("methods/1517/(.*)", "/article/install-cinnamon-on-ubuntu-1204/"),
("methods/1363/(.*)", "/article/30-x-alcl3/"),
("methods/19/(.*)", "/article/5x-western-blot-loading-buffer/"),
("methods/1467/(.*)", "/article/pcr-product-clean-up-sapexo/"),
("methods/28/(.*)", "/article/formol-sublimate-fixation/"),
("methods/49/(.*)", "/article/organotypic-raft-culture-of-phks/"),
("methods/1446/(.*)", "/article/tissue-preparation-for-vibratome-sectioning/"),
("methods/1351/(.*)", "/article/1-m-hepes-ph-70/"),
("methods/1450/(.*)", "/article/cresyl-violet-staining-nissl-staining/"),
("methods/119/(.*)", "/article/dna-extraction-from-agarose-gels-spin-column/"),
("methods/1374/(.*)", "/article/immunostaining-of-paraffin-sections/"),
("methods/24/(.*)", "/article/proteinase-k-treatment/"),
("methods/1452/(.*)", "/article/dewaxing-paraffin-sections/"),
("methods/1524/(.*)", "/article/django-threaded-comments/"),
("methods/1369/(.*)", "/article/l-b-broth/"),
("methods/1436/(.*)", "/article/colloidal-coomassie-blue-stain/"),
("methods/1506/(.*)", "/article/quickly-serve-a-folder-via-web-server/"),
("methods/1350/(.*)", "/article/1m-mgso4/"),
("methods/1448/(.*)", "/article/immunohistochemistry-with-tsa/"),
("methods/1498/(.*)", "/article/dna-extraction-from-cheek-cells/"),
("methods/1376/(.*)", "/article/dna-ligation/"),
("methods/1530/(.*)", "/article/kill-unresponsive-applications-on-linux/"),
("methods/1505/(.*)", "/article/find-top-404-error-pages-apache/"),
("methods/22/(.*)", "/article/preparation-for-microdissection-paraffinfrozen/"),
("methods/1426/(.*)", "/article/silica-based-plasmid-miniprep-vacuum-manifold/"),
("methods/47/(.*)", "/article/raft-culture-media/"),
("methods/40/(.*)", "/article/chromosome-fish/"),
("methods/1451/(.*)", "/article/luxol-fast-blue-staining/"),
("methods/32/(.*)", "/article/fixation-with-paraformaldehyde/"),
("methods/1393/(.*)", "/article/heparanase-western-blotting/"),
("methods/1338/(.*)", "/article/phem-500-mls-2x/"),
("methods/46/(.*)", "/article/pcr-mutagenesis/"),
("methods/1526/(.*)", "/article/bash-command-substitution/"),
("methods/1337/(.*)", "/article/50-mm-tris-ph-80-10-mm-edta/"),
("methods/37/(.*)", "/article/measuring-cell-fluorescence-using-imagej/"),
("methods/1423/(.*)", "/article/rna-isolation-trizol-method/"),
("methods/1345/(.*)", "/article/high-salt-buffer/"),
("methods/1352/(.*)", "/article/1-m-pipes-ph-69/"),
("methods/1500/(.*)", "/article/crude-depletion-conditions-for-xkcm1/"),
("methods/1388/(.*)", "/article/endotoxin-assay/"),
("methods/1381/(.*)", "/article/lacritin-pkca-signaling-assay/"),
("methods/1373/(.*)", "/article/immunostaining-of-cells-adherent-to-coverslips/"),
("methods/1473/(.*)", "/article/use-screen-to-manage-persistent-sessions/"),
("methods/1508/(.*)", "/article/set-cdpath-to-ease-folder-navigation/"),
("methods/1492/(.*)", "/article/re-execute-command-line-with/"),
("methods/1494/(.*)", "/article/antibody-diluent-for-ihc/"),
("methods/44/(.*)", "/article/bacterial-colony-screening-by-pcr/"),
("methods/1/(.*)", "/article/immunohistochemistry/"),
("methods/15/(.*)", "/article/silaneacetone-silanized-slides/"),
("methods/1443/(.*)", "/article/zymolyase-plasmid-recovery-from-yeast/"),
("methods/121/(.*)", "/article/dna-extraction-from-agarose-gels-paper-strip/"),
("methods/1445/(.*)", "/article/animal-trans-cardial-perfusion-technique/"),
("methods/1348/(.*)", "/article/pmg-buffer/"),
("methods/1365/(.*)", "/article/150-mm-mg-amp-pnp/"),
]

NEW = [
"misc/01-m-glycine-hcl-ph-27",
"misc/05-m-edta",
"misc/05-m-egta-stock",
"misc/05-m-na2co3",
"misc/1-m-hepes-ph-70",
"misc/1-m-kcl-stock",
"misc/1-m-pipes-ph-69",
"misc/10-ammonium-persulphate-solution",
"misc/10-m-naoh",
"misc/10-x-column-buffer",
"misc/100-mm-mgatp-stock",
"misc/100-mm-mggtp",
"misc/100-mm-sodium-orthovanadate",
"misc/100mm-tris-buffer",
"misc/10x-tris-buffer",
"misc/150-mm-mg-amp-pnp",
"misc/1m-dithiothreitol-dtt",
"misc/1m-mgso4",
"misc/20-x-energy-regeneration-system",
"misc/2x-rapid-ligation-buffer",
"misc/3-m-ki",
"misc/30-mm-mg-gtp-g-s",
"misc/30-x-alcl3",
"misc/30-x-naf",
"misc/36-mm-brefeldin-a",
"misc/5-m-nacl",
"misc/50-mm-tris-ph-80-10-mm-edta",
"misc/5x-western-blot-loading-buffer",
"misc/8-paraformaldehyde-for-immunofluorescence",
"misc/automatic-unzipuntar-using-correct-tool",
"misc/brdu-incorporation-for-raft-cultures",
"misc/cell-adhesion",
"misc/cells-in-suspension",
"misc/chemiluminescent-detection",
"misc/chrome-alum-gelatin-slide-coating",
"misc/chromosome-fish",
"misc/collagen-gel-containing-3t3-fibroblasts",
"misc/colloidal-coomassie-blue-solution",
"misc/colloidal-coomassie-blue-stain",
"misc/cosmid-low-copy-plasmid-prep",
"misc/cresyl-violet-staining-nissl-staining",
"misc/crude-depletion-conditions-for-xkcm1",
"misc/csf-extract-prep-for-spindle-assembly",
"misc/ems-mutagenesis",
"misc/endotoxin-assay",
"misc/frozen-yeast-competent-cells",
"misc/heparan-sulfate-chain-analysis",
"misc/heparanase-western-blotting",
"misc/high-salt-buffer",
"misc/homogenization-buffer",
"misc/hss-depletion-conditions-for-xkcm1",
"misc/isolation-buffer",
"misc/isolation-of-ldl-from-human-plasma",
"misc/l-b-broth",
"misc/lacritin-calcium-signaling-assay",
"misc/lacritin-ip3-assay",
"misc/lacritin-pkca-signaling-assay",
"misc/lb-agar-plates",
"misc/m9-plates-leu",
"misc/microtubule-spindowns-from-extracts",
"misc/organotypic-raft-culture-of-phks",
"misc/pbs-1x-in-1l",
"misc/pbs-5x-in-500-mls",
"misc/phem-500-mls-2x",
"misc/plc-buffer-for-immunoprecipitation",
"misc/pm-buffer",
"misc/pmg-buffer",
"misc/preparation-for-microdissection-polyester",
"misc/raft-culture-media",
"misc/rotary-shadowing",
"misc/silica-based-plasmid-miniprep-vacuum-manifold",
"misc/silica-suspension-for-plasmid-recovery",
"misc/sodium-citrate-buffer",
"misc/tear-collection-method",
"misc/tmp-uv-integration",
"misc/transformation-of-frozen-saccharomyces-cerevisiae",
"misc/using-a-gel-doc-system",
"misc/valap",
"misc/x-gal-overlay-assay-for-yeast-plates",
"misc/zymolyase-plasmid-recovery-from-yeast",
"biochemistry/extracting-cholesterol-and-lipids-from-cells",
"biochemistry/extracting-cholesterol-and-lipids-from-cells-0",
"biochemistry/in-gel-tryptic-digest-for-protein-id-by-ms",
"biochemistry/purification-of-6x-his-proteins",
"cell-biology/cell-culture-freezing-media",
"cell-biology/hl-60-differentiation-to-neutrophilsmonocytes",
"cell-biology/restoration-from-dmso-cryopreservation",
"cell-biology/differentiation-to-m1m2-macrophages-gm-csfm-csf",
"cell-biology/primary-monocyte-differentiation-dcs-gm-csfil-4",
"histology/acetic-alcohol-fixation",
"histology/antibody-diluent-for-ihc",
"histology/bouins-fluid-fixation",
"histology/c-elegans-embryo-staining",
"histology/carnoys-fluid-fixation",
"histology/cresyl-violet-staining-nissl-staining",
"histology/dewaxing-paraffin-sections",
"histology/ethanol-fixation-for-flow-cytometry",
"histology/fixation-with-paraformaldehyde",
"histology/fixingpelleting-chromatin-for-immunofluorescence",
"histology/formaldehyde-fixation-for-flow-cytometry",
"histology/formol-sublimate-fixation",
"histology/haemotoxylin-and-eosin-staining",
"histology/hellys-fluid-fixation",
"histology/immunohistochemistry-cultured-cellsmonolayers",
"histology/immunohistochemistry-with-tsa",
"histology/immunohistochemistry",
"histology/immunostaining-of-cells-adherent-to-coverslips",
"histology/immunostaining-of-paraffin-sections",
"histology/luxol-fast-blue-staining",
"histology/michels-fixative-for-immunofluorescence",
"histology/mounting-media",
"histology/neuron-recovery-of-neurobiotinbiocytin-cells",
"histology/neutral-buffered-formalin-fixation",
"histology/nickel-dab-n-dab-labeling",
"histology/preparation-for-microdissection-paraffinfrozen",
"histology/silaneacetone-silanized-slides",
"histology/tissue-preparation-for-vibratome-sectioning",
"histology/zenkers-fluid-fixation",
"imaging/animal-trans-cardial-perfusion-technique",
"imaging/dot-blot-analysis-with-imagej",
"imaging/mowiol-aqueous-mounting-media",
"imaging/dapi-counterstain-adherent-cellssections",
"imaging/measuring-cell-fluorescence-using-imagej",
"immunology/antibody-purification-using-blotted-antigen",
"immunology/b-cell-enrichment-via-dynabeads",
"immunology/generic-quantitative-sandwich-elisa",
"immunology/macs-cd14-separation-of-monocytes",
"immunology/purification-of-anti-peptide-antibody",
"immunology/testing-rabbit-bleeds-by-elisa",
"model-organisms/c-elegans-immunoprecipitation.rst",
"model-organisms/embryo-4d-micro-zeiss-axioplan-2-axiovision-45.rst",
"model-organisms/embryo-4d-microscopy-mounting.rst",
"molecular-biology/5x-long-pcr-buffer",
"molecular-biology/6x-dna-loading-buffer-for-agarose",
"molecular-biology/agarose-gel-electrophoresis",
"molecular-biology/apes-treatment-of-slides",
"molecular-biology/bacterial-colony-screening-by-pcr",
"molecular-biology/bacterial-mediated-rnai",
"molecular-biology/c-elegans-microinjection",
"molecular-biology/c-elegans-single-worm-pcr",
"molecular-biology/c-elegans-total-genomic-dna-preparation",
"molecular-biology/determining-dna-concentrations-for-ligations",
"molecular-biology/dna-extraction-chelex",
"molecular-biology/dna-extraction-from-agarose-gels-dialysis-tubing",
"molecular-biology/dna-extraction-from-agarose-gels-paper-strip",
"molecular-biology/dna-extraction-from-agarose-gels-spin-column",
"molecular-biology/dna-extraction-from-cheek-cells",
"molecular-biology/dna-fragment-isolation",
"molecular-biology/dna-ligation",
"molecular-biology/excision-of-clones-as-pbluescript-from-lzapii",
"molecular-biology/in-situ-hybridisation-to-alpha-satellite-sequences",
"molecular-biology/lacritin-stimulated-cell-proliferation-assay",
"molecular-biology/measuring-dna-contour-lengths-with-imagej",
"molecular-biology/metabolite-extraction-from-supernatant-cells",
"molecular-biology/pcr-mutagenesis",
"molecular-biology/pcr-product-clean-up-sapexo",
"molecular-biology/phosphatase-removal-of-po4-groups-from-dna",
"molecular-biology/preparation-of-competent-xli-blue-mrf-cells",
"molecular-biology/preparation-of-sonicated-salmon-sperm-dna",
"molecular-biology/proteinase-k-treatment",
"molecular-biology/retroviral-infection-of-phks",
"molecular-biology/retrovirus-titration",
"molecular-biology/rna-isolation-trizol-method",
"molecular-biology/t-a-cloning-vectors",
"molecular-biology/transformation-of-plasmid-dna-to-e-coli",
"molecular-biology/transformation-of-xli-blue-mrf-competent-cells",
]

htaccess_rules = []

for o,n in CURRENT:
    match_str = n.replace('/article/','').rstrip('/')
    
    for u in NEW:
        if u.split('/')[1] == match_str:
            # Found it
            htaccess_rules.append("RewriteRule ^%s http://theolb.readthedocs.org/en/latest/%s.html [R=301,L]" % (o, u) )
            htaccess_rules.append("RewriteRule ^%s http://theolb.readthedocs.org/en/latest/%s.html [R=301,L]" % (n[1:], u) )

print '\n'.join( htaccess_rules )